import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";
import reactHooks from "eslint-plugin-react-hooks";
import nextPlugin from "@next/eslint-plugin-next";

// Layering guard (non-negotiable #2): controllers and routes must never import
// models or adapters directly — only services touch models, and only services
// reach third-party integrations. Enforced statically here.
const noModelImports = {
  files: ["apps/api/src/controllers/**/*.ts", "apps/api/src/routes/**/*.ts"],
  rules: {
    "no-restricted-imports": [
      "error",
      {
        patterns: [
          {
            group: ["**/models/*", "**/models"],
            message:
              "Controllers y routes no acceden a models directamente. Usa la capa services.",
          },
          {
            group: ["**/adapters/*", "**/adapters"],
            message:
              "Controllers y routes no acceden a adapters directamente. Usa la capa services.",
          },
        ],
      },
    ],
  },
};

// Frontend: React/Next rules apply only under apps/web. The layering guard
// above has no equivalent here; the frontend's equivalent boundary (no
// component writes a colour or a font-family literal) is enforced by a test,
// not eslint (apps/web/tests/designTokens.test.ts).
const webConfig = {
  files: ["apps/web/**/*.{ts,tsx}"],
  plugins: { "react-hooks": reactHooks, "@next/next": nextPlugin },
  // rootDir tells next/core-web-vitals rules (e.g. no-html-link-for-pages)
  // where the Next app actually lives — this repo's root is the monorepo,
  // not apps/web.
  settings: { next: { rootDir: "apps/web" } },
  rules: {
    ...reactHooks.configs.recommended.rules,
    ...nextPlugin.configs["core-web-vitals"].rules,
  },
};

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      "**/node_modules/**",
      "**/.next/**",
      // Autogenerated by Next; "should not be edited" per its own header.
      "**/next-env.d.ts",
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  noModelImports,
  webConfig,
  {
    // Test files and config are looser: no type-checked linting noise.
    files: ["**/*.config.{ts,mjs,js}", "**/tests/**/*.{ts,tsx}"],
    ...tseslint.configs.disableTypeChecked,
  },
  prettier,
);
